import Airport from '../models/airport.model';

export const seedAirports = async () => {
  try {
    // Check if there are existing airports in the database
    const existingAirports = await Airport.countDocuments();

    if (existingAirports > 0) {
      console.log('Airports data already exists. Skipping seeding.');
      return;
    }

    // Sample data to seed
    const airports = [
      {
        cityName: 'New York',
        countryName: 'United States',
        countryCode: 'US',
        countryCode3Letter: 'USA',
        airportName: 'John F. Kennedy International Airport',
        airportCode: 'JFK',
        cityCode: 'NYC',
        insGeoCode: 40,
        continentName: 'North America',
        continentCode: 'NA',
        languageCode: 'EN',
      },
      {
        cityName: 'London',
        countryName: 'United Kingdom',
        countryCode: 'GB',
        countryCode3Letter: 'GBR',
        airportName: 'Heathrow Airport',
        airportCode: 'LHR',
        cityCode: 'LON',
        insGeoCode: 51,
        continentName: 'Europe',
        continentCode: 'EU',
        languageCode: 'EN',
      },
      {
        cityName: 'Aizawl',
        countryName: 'India',
        countryCode: 'IN',
        countryCode3Letter: '',
        airportName: 'Aizawl Airport',
        airportCode: 'AJL',
        cityCode: 'AJL',
        continentName: 'Asia',
        continentCode: 'ASI',
        languageCode: 'EN',
      },
      {
        cityName: 'Balurghat',
        countryName: 'India',
        countryCode: 'IN',
        countryCode3Letter: '',
        airportName: 'Balurghat Airport',
        airportCode: 'RGH',
        cityCode: 'RGH',
        continentName: 'Asia',
        continentCode: 'ASI',
        languageCode: 'EN',
      },
      {
        cityName: 'Belgaum',
        countryName: 'India',
        countryCode: 'IN',
        countryCode3Letter: '',
        airportName: 'Sambra Airport',
        airportCode: 'IXG',
        cityCode: 'IXG',
        continentName: 'Asia',
        continentCode: 'ASI',
        languageCode: 'EN',
      },
      {
        cityName: 'Bhavnagar',
        countryName: 'India',
        countryCode: 'IN',
        countryCode3Letter: '',
        airportName: 'Bhavnagar Airport',
        airportCode: 'BHU',
        cityCode: 'BHU',
        continentName: 'Asia',
        continentCode: 'ASI',
        languageCode: 'EN',
      },
      {
        cityName: 'Chandigarh',
        countryName: 'India',
        countryCode: 'IN',
        countryCode3Letter: '',
        airportName: 'Chandigarh Airport',
        airportCode: 'IXC',
        cityCode: 'IXC',
        continentName: 'Asia',
        continentCode: 'ASI',
        languageCode: 'EN',
      },
      {
        cityName: 'Coimbatore',
        countryName: 'India',
        countryCode: 'IN',
        countryCode3Letter: '',
        airportName: 'Peelamedu Airport',
        airportCode: 'CJB',
        cityCode: 'CJB',
        continentName: 'Asia',
        continentCode: 'ASI',
        languageCode: 'EN',
      },
      {
        cityName: 'Dehra Dun',
        countryName: 'India',
        countryCode: 'IN',
        countryCode3Letter: '',
        airportName: 'Dehra Dun Airport',
        airportCode: 'DED',
        cityCode: 'DED',
        continentName: 'Asia',
        continentCode: 'ASI',
        languageCode: 'EN',
      },
      {
        cityName: 'Diu',
        countryName: 'India',
        countryCode: 'IN',
        countryCode3Letter: '',
        airportName: 'Diu Airport',
        airportCode: 'DIU',
        cityCode: 'DIU',
        continentName: 'Asia',
        continentCode: 'ASI',
        languageCode: 'EN',
      },
      {
        cityName: 'Gorakhpur',
        countryName: 'India',
        countryCode: 'IN',
        countryCode3Letter: '',
        airportName: 'Gorakhpur Airport',
        airportCode: 'GOP',
        cityCode: 'GOP',
        continentName: 'Asia',
        continentCode: 'ASI',
        languageCode: 'EN',
      },
      {
        cityName: 'Jammu',
        countryName: 'India',
        countryCode: 'IN',
        countryCode3Letter: '',
        airportName: 'Satwari Airport',
        airportCode: 'IXJ',
        cityCode: 'IXJ',
        continentName: 'Asia',
        continentCode: 'ASI',
        languageCode: 'EN',
      },
      {
        cityName: 'Kanpur',
        countryName: 'India',
        countryCode: 'IN',
        countryCode3Letter: '',
        airportName: 'Kanpur Airport',
        airportCode: 'KNU',
        cityCode: 'KNU',
        continentName: 'Asia',
        continentCode: 'ASI',
        languageCode: 'EN',
      },
      {
        cityName: 'Keshod',
        countryName: 'India',
        countryCode: 'IN',
        countryCode3Letter: '',
        airportName: 'Keshod Airport',
        airportCode: 'IXK',
        cityCode: 'IXK',
        continentName: 'Asia',
        continentCode: 'ASI',
        languageCode: 'EN',
      },
      {
        cityName: 'Kolkata',
        countryName: 'India',
        countryCode: 'IN',
        countryCode3Letter: '',
        airportName: 'Netaji Subhash Chandra Bose Airport',
        airportCode: 'CCU',
        cityCode: 'CCU',
        continentName: 'Asia',
        continentCode: 'ASI',
        languageCode: 'EN',
      },
      {
        cityName: 'Kullu',
        countryName: 'India',
        countryCode: 'IN',
        countryCode3Letter: '',
        airportName: 'Bhuntar Airport',
        airportCode: 'KUU',
        cityCode: 'KUU',
        continentName: 'Asia',
        continentCode: 'ASI',
        languageCode: 'EN',
      },
      {
        cityName: 'Lilabari',
        countryName: 'India',
        countryCode: 'IN',
        countryCode3Letter: '',
        airportName: 'Lilabari Airport',
        airportCode: 'IXI',
        cityCode: 'IXI',
        continentName: 'Asia',
        continentCode: 'ASI',
        languageCode: 'EN',
      },
      {
        cityName: 'Mangalore',
        countryName: 'India',
        countryCode: 'IN',
        countryCode3Letter: '',
        airportName: 'Bajpe Airport',
        airportCode: 'IXE',
        cityCode: 'IXE',
        continentName: 'Asia',
        continentCode: 'ASI',
        languageCode: 'EN',
      },
      {
        cityName: 'Pantnagar',
        countryName: 'India',
        countryCode: 'IN',
        countryCode3Letter: '',
        airportName: 'Pantnagar Airport',
        airportCode: 'PGH',
        cityCode: 'PGH',
        continentName: 'Asia',
        continentCode: 'ASI',
        languageCode: 'EN',
      },
      {
        cityName: 'Pasighat',
        countryName: 'India',
        countryCode: 'IN',
        countryCode3Letter: '',
        airportName: 'Pasighat Airport',
        airportCode: 'IXT',
        cityCode: 'IXT',
        continentName: 'Asia',
        continentCode: 'ASI',
        languageCode: 'EN',
      },
      {
        cityName: 'Pathankot',
        countryName: 'India',
        countryCode: 'IN',
        countryCode3Letter: '',
        airportName: 'Pathankot Airport',
        airportCode: 'IXP',
        cityCode: 'IXP',
        continentName: 'Asia',
        continentCode: 'ASI',
        languageCode: 'EN',
      },
      {
        cityName: 'Porbandar',
        countryName: 'India',
        countryCode: 'IN',
        countryCode3Letter: '',
        airportName: 'Porbandar Airport',
        airportCode: 'PBD',
        cityCode: 'PBD',
        continentName: 'Asia',
        continentCode: 'ASI',
        languageCode: 'EN',
      },
      {
        cityName: 'Rajahmundry',
        countryName: 'India',
        countryCode: 'IN',
        countryCode3Letter: '',
        airportName: 'Rajahmundry Airport',
        airportCode: 'RJA',
        cityCode: 'RJA',
        continentName: 'Asia',
        continentCode: 'ASI',
        languageCode: 'EN',
      },
      {
        cityName: 'Shillong',
        countryName: 'India',
        countryCode: 'IN',
        countryCode3Letter: '',
        airportName: 'Shillong Airport',
        airportCode: 'SHL',
        cityCode: 'SHL',
        continentName: 'Asia',
        continentCode: 'ASI',
        languageCode: 'EN',
      },
      {
        cityName: 'Simla',
        countryName: 'India',
        countryCode: 'IN',
        countryCode3Letter: '',
        airportName: 'Simla Airport',
        airportCode: 'SLV',
        cityCode: 'SLV',
        continentName: 'Asia',
        continentCode: 'ASI',
        languageCode: 'EN',
      },
      {
        cityName: 'Tezpur',
        countryName: 'India',
        countryCode: 'IN',
        countryCode3Letter: '',
        airportName: 'Salonibari Airport',
        airportCode: 'TEZ',
        cityCode: 'TEZ',
        continentName: 'Asia',
        continentCode: 'ASI',
        languageCode: 'EN',
      },
      {
        cityName: 'Udaipur',
        countryName: 'India',
        countryCode: 'IN',
        countryCode3Letter: '',
        airportName: 'Dabok Airport',
        airportCode: 'UDR',
        cityCode: 'UDR',
        continentName: 'Asia',
        continentCode: 'ASI',
        languageCode: 'EN',
      },
      {
        cityName: 'Vidyanagar',
        countryName: 'India',
        countryCode: 'IN',
        countryCode3Letter: '',
        airportName: 'Vidyanagar Airport',
        airportCode: 'VDY',
        cityCode: 'VDY',
        continentName: 'Asia',
        continentCode: 'ASI',
        languageCode: 'EN',
      },
      {
        cityName: 'Amritsar',
        countryName: 'India',
        countryCode: 'IN',
        countryCode3Letter: '',
        airportName: 'Raja Sansi Airport',
        airportCode: 'ATQ',
        cityCode: 'ATQ',
        continentName: 'Asia',
        continentCode: 'ASI',
        languageCode: 'EN',
      },
      {
        cityName: 'Chennai',
        countryName: 'India',
        countryCode: 'IN',
        countryCode3Letter: '',
        airportName: 'Chennai International Airport',
        airportCode: 'MAA',
        cityCode: 'MAA',
        continentName: 'Asia',
        continentCode: 'ASI',
        languageCode: 'EN',
      },
      {
        cityName: 'New Delhi',
        countryName: 'India',
        countryCode: 'IN',
        countryCode3Letter: '',
        airportName: 'Indira Gandhi International Airport',
        airportCode: 'DEL',
        cityCode: 'DEL',
        continentName: 'Asia',
        continentCode: 'ASI',
        languageCode: 'EN',
      },
      {
        cityName: 'Gaya',
        countryName: 'India',
        countryCode: 'IN',
        countryCode3Letter: '',
        airportName: 'Gaya Airport',
        airportCode: 'GAY',
        cityCode: 'GAY',
        continentName: 'Asia',
        continentCode: 'ASI',
        languageCode: 'EN',
      },
      {
        cityName: 'Hyderabad',
        countryName: 'India',
        countryCode: 'IN',
        countryCode3Letter: '',
        airportName: 'Rajiv Gandhi International Airport',
        airportCode: 'HYD',
        cityCode: 'HYD',
        continentName: 'Asia',
        continentCode: 'ASI',
        languageCode: 'EN',
      },
      {
        cityName: 'Mumbai',
        countryName: 'India',
        countryCode: 'IN',
        countryCode3Letter: '',
        airportName: 'Chhatrapati Shivaji Maharaj International Airport',
        airportCode: 'BOM',
        cityCode: 'BOM',
        continentName: 'Asia',
        continentCode: 'ASI',
        languageCode: 'EN',
      },
      {
        cityName: 'Port Blair',
        countryName: 'India',
        countryCode: 'IN',
        countryCode3Letter: '',
        airportName: 'Veer Savarkar International Airport',
        airportCode: 'IXZ',
        cityCode: 'IXZ',
        continentName: 'Asia',
        continentCode: 'ASI',
        languageCode: 'EN',
      },
      {
        cityName: 'Tiruchirappalli',
        countryName: 'India',
        countryCode: 'IN',
        countryCode3Letter: '',
        airportName: 'Tiruchirappalli International Airport',
        airportCode: 'TRZ',
        cityCode: 'TRZ',
        continentName: 'Asia',
        continentCode: 'ASI',
        languageCode: 'EN',
      },
    ];
    

    // Insert sample data
    await Airport.insertMany(airports);
    console.log('Airports seeded successfully');
  } catch (error) {
    console.error('Failed to seed airports:', error);
  }
};
